#!/usr/bin/env node

/**
 * Module dependencies.
 */

var app = require('./app.js');
var debug = require('debug')('netform-node:server');
var http = require('http');

/**
 * Get port from environment and store in Express.
 */

var server_port = normalizePort(process.env.OPENSHIFT_NODEJS_PORT || '3000');
var server_ip_address = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';
var server_dns_hostname = process.env.OPENSHIFT_APP_DNS || 'localhost';

global.isLocal = server_dns_hostname=='localhost'?true:false
console.log("host:",server_dns_hostname,"| isLocal:",global.isLocal)

app.set('port', server_port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */
server.listen(server_port, server_ip_address, function () {
  console.log( "Listening on " + server_ip_address + ", port " + server_port )
});



//server.listen(port);
server.on('error', onError);
server.on('listening', onListening);

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
